### ISSUE TITLE
Suggestion to add LLMUnity

### ISSUE THREAD

**Issue by amakropoulos** [Yuan-ManX/ai-game-devtools#108]
Thank you for this awesome guide :tada: !

I'd love it if you could add [LLMUnity](https://github.com/undreamai/LLMUnity), the open-source Unity plugin to run LLMs directly within Unity (no third-party APIs or servers).
Thanks for the consideration :slightly_smiling_face: !

**Comment by Yuan-ManX** [comment]
Awesome!

**Comment by amakropoulos** [comment]
Thank you!
